# Generated by Django 3.2.5 on 2022-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_description', models.TextField(max_length=1000)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('book_review', models.TextField(max_length=1000)),
            ],
        ),
    ]
