# Generated by Django 3.2.5 on 2022-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshelf', '0002_book_item_book_acquired'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_item',
            name='book_read',
            field=models.BooleanField(default=None),
        ),
    ]
