# Generated by Django 3.2.5 on 2022-05-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshelf', '0003_book_item_book_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_item',
            name='book_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book_item',
            name='book_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='book_item',
            name='book_review',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book_item',
            name='book_year',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
    ]
